name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # JOB 1: Validate that the code isn't broken
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test Docker Build
        # This ensures your Dockerfile is valid before deploying
        run: docker build . --file Dockerfile --tag test-build

  # JOB 2: Deploy to Hugging Face (Runs only if build-test passes)
  sync-to-huggingface:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Space
        env:
          # You must set these secrets in your GitHub Repo Settings
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: "YOUR_HF_USERNAME"  # Replace or use a secret
          HF_SPACE_NAME: "YOUR_SPACE_NAME" # Replace or use a secret
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          # This command pushes your current code to the HF Space remote
          git push --force https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$HF_SPACE_NAME main